/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as RastreabilidadeRouteImport } from './routes/rastreabilidade'
import { Route as OrigemRouteImport } from './routes/origem'
import { Route as OportunidadesRouteImport } from './routes/oportunidades'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CertificacaoRouteImport } from './routes/certificacao'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as OrigemLoteRouteImport } from './routes/origem.$lote'
import { Route as HistoriasSitioBoaEsperancaRouteImport } from './routes/historias.sitio-boa-esperanca'
import { Route as DashboardReputacaoRouteImport } from './routes/dashboard.reputacao'
import { Route as DashboardQrcodeRouteImport } from './routes/dashboard.qrcode'
import { Route as DashboardProdutosRouteImport } from './routes/dashboard.produtos'
import { Route as DashboardPerfilRouteImport } from './routes/dashboard.perfil'
import { Route as DashboardPedidosRouteImport } from './routes/dashboard.pedidos'
import { Route as DashboardOportunidadesRouteImport } from './routes/dashboard.oportunidades'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard.configuracoes'
import { Route as DashboardCertificacoesRouteImport } from './routes/dashboard.certificacoes'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreabilidadeRoute = RastreabilidadeRouteImport.update({
  id: '/rastreabilidade',
  path: '/rastreabilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const OrigemRoute = OrigemRouteImport.update({
  id: '/origem',
  path: '/origem',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesRoute = OportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificacaoRoute = CertificacaoRouteImport.update({
  id: '/certificacao',
  path: '/certificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const OrigemLoteRoute = OrigemLoteRouteImport.update({
  id: '/$lote',
  path: '/$lote',
  getParentRoute: () => OrigemRoute,
} as any)
const HistoriasSitioBoaEsperancaRoute =
  HistoriasSitioBoaEsperancaRouteImport.update({
    id: '/historias/sitio-boa-esperanca',
    path: '/historias/sitio-boa-esperanca',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardReputacaoRoute = DashboardReputacaoRouteImport.update({
  id: '/reputacao',
  path: '/reputacao',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQrcodeRoute = DashboardQrcodeRouteImport.update({
  id: '/qrcode',
  path: '/qrcode',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProdutosRoute = DashboardProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerfilRoute = DashboardPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPedidosRoute = DashboardPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOportunidadesRoute = DashboardOportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCertificacoesRoute = DashboardCertificacoesRouteImport.update({
  id: '/certificacoes',
  path: '/certificacoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/certificacao': typeof CertificacaoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/marketplace': typeof MarketplaceRoute
  '/oportunidades': typeof OportunidadesRoute
  '/origem': typeof OrigemRouteWithChildren
  '/rastreabilidade': typeof RastreabilidadeRoute
  '/sobre': typeof SobreRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/certificacoes': typeof DashboardCertificacoesRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/oportunidades': typeof DashboardOportunidadesRoute
  '/dashboard/pedidos': typeof DashboardPedidosRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard/qrcode': typeof DashboardQrcodeRoute
  '/dashboard/reputacao': typeof DashboardReputacaoRoute
  '/historias/sitio-boa-esperanca': typeof HistoriasSitioBoaEsperancaRoute
  '/origem/$lote': typeof OrigemLoteRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/certificacao': typeof CertificacaoRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/marketplace': typeof MarketplaceRoute
  '/oportunidades': typeof OportunidadesRoute
  '/origem': typeof OrigemRouteWithChildren
  '/rastreabilidade': typeof RastreabilidadeRoute
  '/sobre': typeof SobreRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/certificacoes': typeof DashboardCertificacoesRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/oportunidades': typeof DashboardOportunidadesRoute
  '/dashboard/pedidos': typeof DashboardPedidosRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard/qrcode': typeof DashboardQrcodeRoute
  '/dashboard/reputacao': typeof DashboardReputacaoRoute
  '/historias/sitio-boa-esperanca': typeof HistoriasSitioBoaEsperancaRoute
  '/origem/$lote': typeof OrigemLoteRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/certificacao': typeof CertificacaoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/marketplace': typeof MarketplaceRoute
  '/oportunidades': typeof OportunidadesRoute
  '/origem': typeof OrigemRouteWithChildren
  '/rastreabilidade': typeof RastreabilidadeRoute
  '/sobre': typeof SobreRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/certificacoes': typeof DashboardCertificacoesRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/oportunidades': typeof DashboardOportunidadesRoute
  '/dashboard/pedidos': typeof DashboardPedidosRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard/qrcode': typeof DashboardQrcodeRoute
  '/dashboard/reputacao': typeof DashboardReputacaoRoute
  '/historias/sitio-boa-esperanca': typeof HistoriasSitioBoaEsperancaRoute
  '/origem/$lote': typeof OrigemLoteRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/certificacao'
    | '/dashboard'
    | '/login'
    | '/mapa'
    | '/marketplace'
    | '/oportunidades'
    | '/origem'
    | '/rastreabilidade'
    | '/sobre'
    | '/dashboard/analytics'
    | '/dashboard/certificacoes'
    | '/dashboard/configuracoes'
    | '/dashboard/oportunidades'
    | '/dashboard/pedidos'
    | '/dashboard/perfil'
    | '/dashboard/produtos'
    | '/dashboard/qrcode'
    | '/dashboard/reputacao'
    | '/historias/sitio-boa-esperanca'
    | '/origem/$lote'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/certificacao'
    | '/login'
    | '/mapa'
    | '/marketplace'
    | '/oportunidades'
    | '/origem'
    | '/rastreabilidade'
    | '/sobre'
    | '/dashboard/analytics'
    | '/dashboard/certificacoes'
    | '/dashboard/configuracoes'
    | '/dashboard/oportunidades'
    | '/dashboard/pedidos'
    | '/dashboard/perfil'
    | '/dashboard/produtos'
    | '/dashboard/qrcode'
    | '/dashboard/reputacao'
    | '/historias/sitio-boa-esperanca'
    | '/origem/$lote'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/certificacao'
    | '/dashboard'
    | '/login'
    | '/mapa'
    | '/marketplace'
    | '/oportunidades'
    | '/origem'
    | '/rastreabilidade'
    | '/sobre'
    | '/dashboard/analytics'
    | '/dashboard/certificacoes'
    | '/dashboard/configuracoes'
    | '/dashboard/oportunidades'
    | '/dashboard/pedidos'
    | '/dashboard/perfil'
    | '/dashboard/produtos'
    | '/dashboard/qrcode'
    | '/dashboard/reputacao'
    | '/historias/sitio-boa-esperanca'
    | '/origem/$lote'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CertificacaoRoute: typeof CertificacaoRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  MapaRoute: typeof MapaRoute
  MarketplaceRoute: typeof MarketplaceRoute
  OportunidadesRoute: typeof OportunidadesRoute
  OrigemRoute: typeof OrigemRouteWithChildren
  RastreabilidadeRoute: typeof RastreabilidadeRoute
  SobreRoute: typeof SobreRoute
  HistoriasSitioBoaEsperancaRoute: typeof HistoriasSitioBoaEsperancaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreabilidade': {
      id: '/rastreabilidade'
      path: '/rastreabilidade'
      fullPath: '/rastreabilidade'
      preLoaderRoute: typeof RastreabilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/origem': {
      id: '/origem'
      path: '/origem'
      fullPath: '/origem'
      preLoaderRoute: typeof OrigemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades': {
      id: '/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof OportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificacao': {
      id: '/certificacao'
      path: '/certificacao'
      fullPath: '/certificacao'
      preLoaderRoute: typeof CertificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/origem/$lote': {
      id: '/origem/$lote'
      path: '/$lote'
      fullPath: '/origem/$lote'
      preLoaderRoute: typeof OrigemLoteRouteImport
      parentRoute: typeof OrigemRoute
    }
    '/historias/sitio-boa-esperanca': {
      id: '/historias/sitio-boa-esperanca'
      path: '/historias/sitio-boa-esperanca'
      fullPath: '/historias/sitio-boa-esperanca'
      preLoaderRoute: typeof HistoriasSitioBoaEsperancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reputacao': {
      id: '/dashboard/reputacao'
      path: '/reputacao'
      fullPath: '/dashboard/reputacao'
      preLoaderRoute: typeof DashboardReputacaoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/qrcode': {
      id: '/dashboard/qrcode'
      path: '/qrcode'
      fullPath: '/dashboard/qrcode'
      preLoaderRoute: typeof DashboardQrcodeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/produtos': {
      id: '/dashboard/produtos'
      path: '/produtos'
      fullPath: '/dashboard/produtos'
      preLoaderRoute: typeof DashboardProdutosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/perfil': {
      id: '/dashboard/perfil'
      path: '/perfil'
      fullPath: '/dashboard/perfil'
      preLoaderRoute: typeof DashboardPerfilRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pedidos': {
      id: '/dashboard/pedidos'
      path: '/pedidos'
      fullPath: '/dashboard/pedidos'
      preLoaderRoute: typeof DashboardPedidosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/oportunidades': {
      id: '/dashboard/oportunidades'
      path: '/oportunidades'
      fullPath: '/dashboard/oportunidades'
      preLoaderRoute: typeof DashboardOportunidadesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/certificacoes': {
      id: '/dashboard/certificacoes'
      path: '/certificacoes'
      fullPath: '/dashboard/certificacoes'
      preLoaderRoute: typeof DashboardCertificacoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCertificacoesRoute: typeof DashboardCertificacoesRoute
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardOportunidadesRoute: typeof DashboardOportunidadesRoute
  DashboardPedidosRoute: typeof DashboardPedidosRoute
  DashboardPerfilRoute: typeof DashboardPerfilRoute
  DashboardProdutosRoute: typeof DashboardProdutosRoute
  DashboardQrcodeRoute: typeof DashboardQrcodeRoute
  DashboardReputacaoRoute: typeof DashboardReputacaoRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCertificacoesRoute: DashboardCertificacoesRoute,
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardOportunidadesRoute: DashboardOportunidadesRoute,
  DashboardPedidosRoute: DashboardPedidosRoute,
  DashboardPerfilRoute: DashboardPerfilRoute,
  DashboardProdutosRoute: DashboardProdutosRoute,
  DashboardQrcodeRoute: DashboardQrcodeRoute,
  DashboardReputacaoRoute: DashboardReputacaoRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OrigemRouteChildren {
  OrigemLoteRoute: typeof OrigemLoteRoute
}

const OrigemRouteChildren: OrigemRouteChildren = {
  OrigemLoteRoute: OrigemLoteRoute,
}

const OrigemRouteWithChildren =
  OrigemRoute._addFileChildren(OrigemRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CertificacaoRoute: CertificacaoRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  MapaRoute: MapaRoute,
  MarketplaceRoute: MarketplaceRoute,
  OportunidadesRoute: OportunidadesRoute,
  OrigemRoute: OrigemRouteWithChildren,
  RastreabilidadeRoute: RastreabilidadeRoute,
  SobreRoute: SobreRoute,
  HistoriasSitioBoaEsperancaRoute: HistoriasSitioBoaEsperancaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
